TrafficProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="top"), name='logout'),
    path('shop/signup/', views.register_user, name='signup'),
    path('app/signup/', views.register_app_user, name='app_signup'),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", views.ArticleDetailView.as_view(), name="detail"),
    #path("update/<int:pk>/", views.ShopUpdate.as_view(), name="update"),
    #path("delete/", views.ArticleDeleteView.as_view(), name="delete"),
    path("tag/create/", views.TagCreateView.as_view(), name="create_tag"),
    path("search/", views.index, name="search"),
]

TrafficProject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'', include('accounts.urls')),
    path(r'', include('olyful.urls')),
]

TrafficProject/olyful/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name="top"),
    path('users/login/', auth_views.LoginView.as_view(template_name='olyful/users_login.html'), name='users_login'),
    path('users/logout/', auth_views.LogoutView.as_view(), name='users_logout'),
    path('shoppage/', views.shoppage, name='shoppage'),
    path('mypage/<int:pk>', views.mypage, name='mypage'),
    path('mypage/<int:pk>/edit', views.edit, name='edit'),
    path('traininfo/', views.traininfo, name='traininfo'),
    #path('', views.SearchResultView.as_view(), name='search'),
]
# MEDIA_ROOTを公開する（アクセス可能にする）
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrafficProject/olyful/models.py
from django.db import models

# Create your models here.

TrafficProject/olyful/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from accounts.models import ShopInfo
from django.views import generic
from django.views.generic import ListView
from django.http import Http404, HttpResponse, JsonResponse #
from django.core import serializers
import json
import time
import olyful.traffic
from . import models
from django.contrib.auth import get_user_model

# Create your views here.
#def top(request):
#    """トップ画面"""
#    return render(request, 'olyful/top.html')

class ArticleListView(generic.ListView):
    #トップ画面
    model = ShopInfo
    template_name = 'olyful/top.html'


@login_required
def shoppage(request):
    shopinfo_list = get_user_model().objects.all()
    context = {'shopinfo_list' : shopinfo_list}
    return render(request, 'olyful/shoppage.html', context)


def mypage(request, pk):
    user = get_object_or_404(User, pk=pk)
    context = {
        'user': user,
    }
    return render(request, 'olyful/mypage.html', context)


def edit(request,pk):
    template_name = "olyful/edit.html"
    try:
        user = User.objects.get(pk=pk)
    except models.User.DoesNotExist:
        raise Http404
    if request.method == "POST":
        user.username = request.POST["username"]
        user.email = request.POST["email"]
        user.save()
        return redirect(mypage,pk)
    context = {"user": user}
    return render(request, template_name, context)

def traininfo(request):
    now = olyful.traffic.time
    trouble_info = olyful.traffic.trouble_info
    major_line = olyful.traffic.major_line
    context = {
        'time': now,
        'trouble_info': trouble_info,
        'major_line': major_line
    }
    return render(request, 'olyful/traininfo.html', context)

TrafficProject/olyful/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <title>{% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<!-- <body>
  <nav class="navbar navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'top' %}">トップページ</a>
      </li>
      {% if request.user.is_authenticated %}
      <a class="nav-link" href="{% url 'mypage' request.user.id %}">マイページ</a>
      <a class="nav-link" href="{% url 'users_logout' %}">ログアウト(ユーザー用)</a>
      {% else %}
      <a class="nav-link" href="{% url 'users_login' %}">ログイン(ユーザー用)</a>
      {% endif %}
      {% block nav_item %}{% endblock %}
    </ul>
  </nav> -->

  <nav class="navbar navbar-expand-sm navbar-light bg-light mt-3 mb-3 border border-warning"">
          <div class="collapse navbar-collapse">
              <ul class="navbar-nav">
                <li>
                  <a class="navbar-brand" href="{% url 'top' %}">　Olyful</a>
                </li>

                  {% if request.user.is_authenticated %}
                  <li class="navbar-text navbar-right">{{ user.username }} さん でログイン中　　</li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'mypage' request.user.id %}">マイページ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'shoppage' %}">店舗ページ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                  </li>

                  {% else %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">ログイン</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:app_signup' %}">会員登録</a>
                  </li>
                  {% endif %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:search' %}">検索</a>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'traininfo' %}">運行情報</a>
                  </li>
              </ul>
          </div>
      </nav>


  <div class="container">
    <div class="card">
      <div class="container">
        {% block jumbotron %}{% endblock %}
      </div>
    </div>
  </div>


</body>
</html>