TrafficProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="top"), name='logout'),
    path('shop/signup/', views.register_user, name='signup'),
    path('app/signup/', views.register_app_user, name='app_signup'),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", views.ArticleDetailView.as_view(), name="detail"),
    #path("update/<int:pk>/", views.ShopUpdate.as_view(), name="update"),
    #path("delete/", views.ArticleDeleteView.as_view(), name="delete"),
    path("tag/create/", views.TagCreateView.as_view(), name="create_tag"),
    path("search/", views.index, name="search"),
]

TrafficProject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'', include('accounts.urls')),
    path(r'', include('olyful.urls')),
]

TrafficProject/olyful/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name="top"),
    path('users/login/', auth_views.LoginView.as_view(template_name='olyful/users_login.html'), name='users_login'),
    path('users/logout/', auth_views.LogoutView.as_view(), name='users_logout'),
    path('shoppage/', views.shoppage, name='shoppage'),
    path('mypage/<int:pk>', views.mypage, name='mypage'),
    path('mypage/<int:pk>/edit', views.edit, name='edit'),
    path('traininfo/', views.traininfo, name='traininfo'),
    #path('', views.SearchResultView.as_view(), name='search'),
]
# MEDIA_ROOTを公開する（アクセス可能にする）
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrafficProject/olyful/models.py
from django.db import models

# Create your models here.

TrafficProject/olyful/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from accounts.models import ShopInfo
from django.views import generic
from django.views.generic import ListView
from django.http import Http404, HttpResponse, JsonResponse #
from django.core import serializers
import json
import time
import olyful.traffic
from . import models
from django.contrib.auth import get_user_model

# Create your views here.
#def top(request):
#    """トップ画面"""
#    return render(request, 'olyful/top.html')

class ArticleListView(generic.ListView):
    #トップ画面
    model = ShopInfo
    template_name = 'olyful/top.html'


@login_required
def shoppage(request):
    shopinfo_list = get_user_model().objects.all()
    context = {'shopinfo_list' : shopinfo_list}
    return render(request, 'olyful/shoppage.html', context)


def mypage(request, pk):
    user = get_object_or_404(User, pk=pk)
    context = {
        'user': user,
    }
    return render(request, 'olyful/mypage.html', context)


def edit(request,pk):
    template_name = "olyful/edit.html"
    try:
        user = User.objects.get(pk=pk)
    except models.User.DoesNotExist:
        raise Http404
    if request.method == "POST":
        user.username = request.POST["username"]
        user.email = request.POST["email"]
        user.save()
        return redirect(mypage,pk)
    context = {"user": user}
    return render(request, template_name, context)

def traininfo(request):
    now = olyful.traffic.time
    trouble_info = olyful.traffic.trouble_info
    major_line = olyful.traffic.major_line
    context = {
        'time': now,
        'trouble_info': trouble_info,
        'major_line': major_line
    }
    return render(request, 'olyful/traininfo.html', context)

TrafficProject/olyful/templates/olyful/edit.html
{% extends 'base/base.html' %}
{% block title %}Mypage{% endblock %}

{% block jumbotron %}
</br>

<h1>編集ページ</h1>
<form action="" method="post">
    {% csrf_token %}
    <p><label for="username_input">ユーザー名</label></p>
    <p><input type="text" name="username" id="username_input" value="{{ user.username }}"></p>
    <p><label for="email">メールアドレス</label></p>
    <p><input type="text" name="email" id="email_input" value="{{ user.email }}"></p>
    <p><button type="submit">更新</button></p>
</form>

{% endblock %}

TrafficProject/olyful/templates/olyful/mypage.html
{% extends 'base/base.html' %}
{% block title %}Mypage{% endblock %}

{% block jumbotron %}
</br>
<h2>こんにちは　@{{ user.username }}さん</h2>
</br>

<table class="table">
    <tbody>
      <tr>
        <th>ユーザー名</th>
        <td>{{ user.username }}</td>
      </tr>

      <tr>
        <th>メールアドレス</th>
        <td>{{ user.email }}</td>
      </tr>
    </tbody>
</table>

<p>プロフィールの編集は <a href="{% url 'edit' user.pk %}">こちら</a></p>

{% endblock %}

TrafficProject/olyful/templates/olyful/search.html
{% extends 'base/base.html' %}
{% block title %}検索結果{% endblock %}
{% load static %}

{% block jumbotron %}
<h1>Search</h1>
<br />
<form action="" method="POST">
  {{ formset.management_form }}
  {% for form in formset %}
  {{ form }}
  {% endfor %}
  {% csrf_token %}
  <button class="btn btn-warning" type="submit">検索</button>
</form>

<br />
<br />

<div class="card-deck row">
  {% for item in shop_list %}
  <div class="col-sm-6">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" src="{{item.thumbnail.url }}">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'accounts:detail' item.pk %}">{{ item.shop_name }}</a><br /></h5>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

TrafficProject/olyful/templates/olyful/shoppage.html
{% extends 'base/base.html' %}
{% block title %}店舗ページ{% endblock %}
{% load static %}

{% block jumbotron %}
<h1>ShopPage</h1>

<img src="{{ user.top.url }}">
<br />

<table class="table">
    <tbody>
      <tr>
        <th>店名</th>
        <td>{{ user.shop_name }}</td>
      </tr>

      <tr>
        <th>住所</th>
        <td>{{ user.address }}</td>
      </tr>

      <tr>
        <th>連絡先</th>
        <td>{{ user.phone }}</td>
      </tr>

      <tr>
        <th>メニュー</th>
        <td>{{ user.menu }}</td>
      </tr>

      <tr>
        <th>特典</th>
        <td>{{ user.special }}</td>
      </tr>
    </tbody>


    <ul>
      <li>編集</li>
      <li>削除</li>
    </ul>

{% endblock %}

TrafficProject/olyful/templates/olyful/top.html
{% extends 'base/base.html' %}
{% block title %}TOP{% endblock %}
{% load static %}

{% block head %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
{% endblock head %}

{% block jumbotron %}
<br>

<div class="card-deck row">
  {% for item in object_list %}
  <div class="col-sm-6">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" src="{{item.thumbnail.url }}">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'accounts:detail' item.pk %}">{{ item.shop_name }}</a><br /></h5>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

TrafficProject/olyful/templates/olyful/traininfo.html
{% extends 'base/base.html' %}
{% block title %}TrainInfomation{% endblock %}
{% load static %}

{% block jumbotron %}
</br>
<h2>運行情報 関東</h2>
<p><font color="#ff0000">{{ time }}</font></p>
</br>
<h3>現在運行情報のある路線</h3>
<p class="ml-sm-3"><b><font color="0000ff">{{ trouble_info | linebreaksbr }}</font></b></p>
</br>
<h3>関東の主要鉄道</h3>
<p class="ml-sm-3"> {{major_line | linebreaksbr}} </p>
<br>
<input class="btn btn-outline-secondary" value="最新情報に更新" onclick="window.location.reload();" />
<br />
<br />
{% endblock %}

TrafficProject/olyful/templates/olyful/users_login.html
{% extends 'base/base.html' %}
{% block title %}Login{% endblock %}

{% block jumbotron %}
<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
        <p>ユーザー名かパスワードが間違っています。もう一度入力してください。</p>
    {% endif %}
    <h2>ログイン</h2>
    <label>ユーザー名</label>
    <input name="username">
    <br>
    <label>パスワード</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン">
</form>
{% endblock %}