TrafficProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="top"), name='logout'),
    path('shop/signup/', views.register_user, name='signup'),
    path('app/signup/', views.register_app_user, name='app_signup'),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", views.ArticleDetailView.as_view(), name="detail"),
    #path("update/<int:pk>/", views.ShopUpdate.as_view(), name="update"),
    #path("delete/", views.ArticleDeleteView.as_view(), name="delete"),
    path("tag/create/", views.TagCreateView.as_view(), name="create_tag"),
    path("search/", views.index, name="search"),
]

TrafficProject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'', include('accounts.urls')),
    path(r'', include('olyful.urls')),
]

TrafficProject/accounts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import RegexValidator

class Tag(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

VENUES_CHOICES = [
    (1, 'オリンピックスタジアム'),
    (2, '東京体育館'),
    (3, '国立代々木競技場'),
    (4, '日本武道館'),
    (5, '東京国際フォーラム'),
    (6, '国技館'),
    (7, '馬事公苑'),
    (8, '武蔵野の森総合スポーツプラザ'),
    (9, '東京スタジアム'),
    (10, '武蔵野の森公園'),
    (11, '有明アリーナ'),
    (12, '有明体操競技場'),
    (13, '有明アーバンスポーツパーク'),
    (14, '有明テニスの森'),
    (15, 'お台場海浜公園'),
    (16, '潮風公園'),
    (17, '青海アーバンスポーツパーク'),
    (18, '大井ホッケー競技場'),
    (19, '海の森クロスカントリーコース'),
    (20, '海の森水上競技場'),
    (21, 'カヌー・スラロームセンター'),
    (22, '夢の島公園アーチェリー場'),
    (23, '東京アクアティクスセンター'),
    (24, '東京辰巳国際水泳場'),
]

class ShopInfo(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    shop_name = models.CharField('店舗名', max_length=40)
    tag = models.ManyToManyField(Tag)
    #venues = models.CharField('最寄りの会場', max_length=60, default="")
    #station = models.CharField('最寄りの駅', max_length=60, default="")
    address = models.CharField('住所', max_length=60, default="")
    phone_regex = RegexValidator(regex=r'^[0-9]+$', message = ("Tell Number must be entered in the format: '09012345678'. Up to 15 digits allowed."))
    phone = models.CharField(validators=[phone_regex], max_length=15, verbose_name='電話番号(半角/ハイフンなし)', default="")
    menu = models.TextField('メニュー', default="")
    special = models.TextField('利用者への特典(クーポン等)', blank=True, null=True)
    shop_image = models.ImageField('店の写真', upload_to='media', default="", blank=True, null=True)

    # shop_imageをリサイズ
    top = ImageSpecField(source="shop_image", processors=[ResizeToFill(700, 500)], format='JPEG')
    thumbnail = ImageSpecField(source='shop_image', processors=[ResizeToFill(250,250)], format="JPEG", options={'quality': 60})
    food = ImageSpecField(source='shop_image', processors=[ResizeToFill(600, 400)], format="JPEG", options={'quality': 75} )

    class Meta:
        permissions = (
            ('create_shoppage', 'Can create shoppage'),
        )

    def __str__(self):
        return self.shop_name

TrafficProject/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm #
from .models import ShopInfo #

class UserCreateForm(UserCreationForm):
    #入力を必須にするため、required=Trueで上書き
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = User
       fields = (
           "username", "email", "password1", "password2"
       )

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError("正しいメールアドレスを指定して下さい。")

        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        else:
            raise ValidationError("このメールアドレスは既に使用されています。別のメールアドレスを指定してください")



"""検索フォーム"""
class BlogForm(ModelForm):
    class Meta:
        model = ShopInfo
        fields = ['shop_name', 'tag']

class BlogSearchForm(forms.Form):
    shop_name = forms.CharField(label='店舗名', required=False)
    tag = forms.CharField(label='タグ', required=False)

BlogSearchFormSet = forms.formset_factory(BlogSearchForm, extra=1)


"""店舗情報更新フォーム"""
class ShopUpdateForm(forms.ModelForm):
    class Meta:
        model = ShopInfo
        fields = ('shop_name', 'tag', 'address', 'phone', 'menu', 'special', 'shop_image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

TrafficProject/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserCreateForm
from django.contrib.auth import login
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views import generic
from .models import ShopInfo,Tag

from django.db.models import Q
from django.views.decorators.http import require_POST
from .forms import BlogForm, BlogSearchFormSet, ShopUpdateForm


def register_user(request):
    """ユーザー登録（店用）"""
    user_form = UserCreateForm(request.POST or None)
    if request.method == "POST" and user_form.is_valid():
        # Userモデルの処理。ログインできるようis_activeをTrueにし保存
        user = user_form.save(commit=False)
        user.is_active = True
        user.save()
        login(request, user, backend="django.contrib.auth.backends.ModelBackend")
        return redirect("accounts:create")

    context = { "user_form": user_form, }
    return render(request, 'accounts/signup.html', context)


class ArticleCreateView(generic.edit.CreateView):
    """店の情報　登録"""
    model = ShopInfo
    fields = ["shop_name","tag","address","phone","menu","special","shop_image"]
    #fields = ["shop_name","tag","venues","station","address","phone","menu","special","shop_image"]
    template_name = "accounts/create.html"
    success_url = reverse_lazy('top')  #POSTが正しく行われた際に飛ばすURL


class ArticleDetailView(generic.DetailView):
    """店の情報を見る"""
    model = ShopInfo
    #shopinfo = Shop.objects.get(pk=pk)
    template_name = "accounts/detail.html"


class TagCreateView(generic.edit.CreateView):
    """タグの作成"""
    model = Tag
    fields = ["name"]
    template_name = "accounts/create-tag.html"
    success_url = reverse_lazy('accounts:create')  #POSTが正しく行われた際に飛ばすURL


def register_app_user(request):
    """ユーザー登録"""
    user_form = UserCreateForm(request.POST or None)
    if request.method == "POST" and user_form.is_valid():

        # Userモデルの処理。ログインできるようis_activeをTrueにし保存
        user = user_form.save(commit=False)
        user.is_active = True
        user.save()

        login(request, user, backend="django.contrib.auth.backends.ModelBackend")

        return redirect("top")

    context = {
        "user_form": user_form,
    }
    return render(request, 'accounts/app_signup.html', context)


def index(request):
    """検索"""
    shop_list = ShopInfo.objects.all()
    formset = BlogSearchFormSet(request.POST or None)
    if request.method == 'POST':
        formset.is_valid()

        queries = []

        for form in formset:
            q_kwargs = {}
            shop_name = form.cleaned_data.get('shop_name')
            if shop_name:
                q_kwargs['shop_name'] = shop_name

            tag = form.cleaned_data.get('tag')
            if tag:
                q_kwargs['tag'] = tag

            if q_kwargs:
                q = Q(**q_kwargs)
                queries.append(q)

        if queries:
            base_query = queries.pop()
            for query in queries:
                base_query |= query
            shop_list = shop_list.filter(base_query)

    return render(request, 'olyful/search.html', {'shop_list': shop_list, 'formset': formset})

"""
#@login_required
class ShopUpdate(generic.UpdateView):
    #情報更新（未）
    model = ShopInfo
    form_class = ShopUpdateForm
    #template_name = 'accounts/update.html'
    template_name = 'update.html'
    success_url = "/"
"""
"""
#@login_required
class ArticleDeleteView(generic.edit.DeleteView):
    #店のページ削除（未）
    model = ShopInfo
    template_name = "accounts/delete.html"
    success_url = reverse_lazy('top')  #POSTが正しく行われた際に飛ばすURL"""

TrafficProject/accounts/templates/accounts/app_signup.html
{% extends 'base/base.html' %}
{% block title %}App SignUp{% endblock %}
{% load static %}

  {% block jumbotron %}
  <h1>会員登録</h1>
  <p>お店を掲載ご希望の方は<a href="{% url 'accounts:signup' %}">こちら</a></p><br />

  <table class="table">
    <form method="POST" action="" enctype="multipart/form-data">
      {% csrf_token %}
      <tbody>
        <tr>
          <th>ユーザー名</th>
          <td>{{user_form.username}}
            {{user_form.username.errors}}</td>
        </tr>

        <tr>
          <th>メールアドレス</th>
          <td>{{user_form.email}}
            {{user_form.email.errors}}</td>
        </tr>

        <tr>
          <th>パスワード</th>
          <td>{{user_form.password1}}
            {{user_form.password1.errors}}</td>
        </tr>

        <tr>
          <th>パスワード(確認)</th>
          <td>{{user_form.password2}}
            {{user_form.password2.errors}}</td>
        </tr>
      </tbody>

      <tr>
        <td><input class="btn btn-warning" type="submit" value="登録">
          <input class="btn btn-outline-secondary" type="reset" value="リセット"></td>
      </tr>

    </form>
  </table>
</body>
{% endblock %}

TrafficProject/accounts/templates/accounts/create-tag.html
{% extends 'base/base.html' %}
{% block title %}新規タグ作成{% endblock %}
{% load static %}

{% block jumbotron %}
    <form method="post">{% csrf_token %}

            {{ form.name }}

        <!-- {{ form.as_p }} -->
        <input class="button-common" type="submit" value="Save">
    </form>
{% endblock %}

TrafficProject/accounts/templates/accounts/create.html
{% extends 'base/base.html' %}
{% block title %}店舗情報登録{% endblock %}
{% load static %}

{% block jumbotron %}
<h1>Shop Infomation</h1>
<table class="table">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <tbody>
      <tr>
        <th>{{ form.shop_name.label_tag }}</th>
        <td>{{ form.shop_name }}</td>
      </tr>

      <tr>
        <th>タグ</th>
        <td>{{ form.tag }} <a href="{% url 'accounts:create_tag' %}">add new TAG</a></td>
      </tr>

      <!-- <tr>
        <th>最寄りの会場</th>
        <td>{{ form.get_status_display }}</td>
      </tr>

      <tr>
        <th>{{ form.station.label_tag }}</th>
        <td>{{ form.station }}</td>
      </tr> -->

      <tr>
        <th>{{ form.address.label_tag }}</th>
        <td>{{ form.address }}</td>
      </tr>

      <tr>
        <th>{{ form.phone.label_tag }}</th>
        <td>{{ form.phone }}
        {{ form.phone.error }}</td>
      </tr>

      <tr>
        <th>{{ form.menu.label_tag }}</th>
        <td>{{ form.menu }}</td>
      </tr>

      <tr>
        <th>{{ form.special.label_tag }}</th>
        <td>{{ form.special }}</td>
      </tr>

      <tr>
        <th>{{ form.shop_image.label_tag }}</th>
        <td>{{ form.shop_image }}</td>
      </tr>
    </tbody>

    <tr>
      <td><input class="btn btn-warning" type="submit" value="登録">
        <input class="btn btn-outline-secondary" type="reset" value="リセット"></td>
    </tr>

  </form>
</table>
</body>
{% endblock %}

TrafficProject/accounts/templates/accounts/detail.html
{% extends 'base/base.html' %}
{% block title %}{{ object.shop_name }}{% endblock %}
{% load static %}

{% block jumbotron %}
<h1>{{ object.shop_name }}</h1>
  <br />
  <img src="{{ object.top.url }}">
  <br />
  <br />
  <p>
    タグ: {% for tag in object.tag.all %}
    {{ tag }}
    {% endfor %}
  </p>

  <table class="table">
      <tbody>
        <tr>
          <th>住所</th>
          <td>{{ object.address }}</td>
        </tr>

        <tr>
          <th>連絡先</th>
          <td>{{ object.phone }}</td>
        </tr>

        <tr>
          <th>メニュー</th>
          <td>{{ object.menu }}</td>
        </tr>

        <tr>
          <th>特典</th>
          <td>{{ object.special }}</td>
        </tr>
      </tbody>

      {% if request.user.id == object.user.id %}
      <p><ul>
        <li>編集</li>
        <li>削除</li>
      </ul></p>
      {% endif %}


  {% endblock %}

TrafficProject/accounts/templates/accounts/signup.html
{% extends 'base/base.html' %}
{% block title %}SignUp{% endblock %}
{% load static %}

  {% block jumbotron %}
  <h1>店舗登録</h1>
  <p>ユーザーの方は<a href="{% url 'accounts:app_signup' %}">こちら</a></p><br />

  <table class="table">
    <form method="POST" action="">
      {% csrf_token %}
      <tbody>
        <tr>
          <th>ユーザー名</th>
          <td>{{user_form.username}}
            {{user_form.username.errors}}</td>
        </tr>

        <tr>
          <th>メールアドレス</th>
          <td>{{user_form.email}}
            {{user_form.email.errors}}</td>
        </tr>

        <tr>
          <th>パスワード</th>
          <td>{{user_form.password1}}
            {{user_form.password1.errors}}</td>
        </tr>

        <tr>
          <th>パスワード(確認)</th>
          <td>{{user_form.password2}}
            {{user_form.password2.errors}}</td>
        </tr>
      </tbody>

      <tr>
        <td><input class="btn btn-warning" type="submit" value="登録">
            <input class="btn btn-outline-secondary" type="reset" value="リセット">
        </td>
      </tr>

    </form>
  </table>
</body>
{% endblock %}

TrafficProject/accounts/templates/accounts/update.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>
{% endblock %}